name: Create Release and Upload Tar File

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set version
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

    - name: Create Tar File
      run: tar -czvf devies-llm-chat-${{ steps.vars.outputs.tag }}.tar.gz LLMEngine ChatGPT-Client-Web executable

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./devies-llm-chat-${{ steps.vars.outputs.tag }}.tar.gz
        asset_name: devies-llm-chat-${{ steps.vars.outputs.tag }}.tar.gz
        asset_content_type: application/gzip
